### PR TITLE
Sgf for Baduk and its subclasses

### PR DESCRIPTION
**Pull request by benjaminpjones**
This diff introduces a class dedicated to SGF, and adds it to the Baduk variant.  This also gives Baduk subclasses SGF capabilities.

I am happy to report that SGF seems to tolerate changes in player order, so variants like Keima are able to be parsed by other programs like OGS.

Screenshot_20240921_130643

### CODE REVIEW

**Comment by SameerDalal** [comment]
That's awesome! Since some of the Baduk subclasses have different board shapes (non square boards) how are you able to calculate the SGF information for those games?

**Review by SameerDalal — COMMENTED** [review]
Looks good!

**Comment by benjaminpjones** [comment]
Thanks!

> Since some of the Baduk subclasses have different board shapes (non square boards) how are you able to calculate the SGF information for those games?

I took the same approach as Quantum - non-square rectangular boards are supported e.g. `SZ[9:19]`, but other graphs will just return some "non-rectangular boards not supported" file.

I might follow up w/ a PR to hide the download button for non-rectangular configs though.

**Comment by SameerDalal** [comment]
Got it!

**Pull request merged**
